apiVersion: v1
kind: Service
metadata:
  name: trakplus-backend
  namespace: trakplus
spec:
  selector:
    app: trakplus-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
