"""initial schema

Revision ID: 13f74a4c16e8
Revises: 
Create Date: 2026-08-30 20:38:20.915118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13f74a4c16e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.Enum('MOVIE', 'TV', 'GAME', 'ANIME', 'MANGA', name='media_type'), nullable=False),
    sa.Column('tmdb_id', sa.String(length=32), nullable=True),
    sa.Column('rawg_id', sa.String(length=32), nullable=True),
    sa.Column('anilist_id', sa.String(length=32), nullable=True),
    sa.Column('mal_id', sa.String(length=32), nullable=True),
    sa.Column('mangadex_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=100)), server_default='{}', nullable=False),
    sa.Column('poster_url', sa.String(length=1000), nullable=True),
    sa.Column('backdrop_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_anilist_id'), 'titles', ['anilist_id'], unique=True)
    op.create_index(op.f('ix_titles_mal_id'), 'titles', ['mal_id'], unique=True)
    op.create_index(op.f('ix_titles_mangadex_id'), 'titles', ['mangadex_id'], unique=True)
    op.create_index(op.f('ix_titles_media_type'), 'titles', ['media_type'], unique=False)
    op.create_index(op.f('ix_titles_rawg_id'), 'titles', ['rawg_id'], unique=True)
    op.create_index(op.f('ix_titles_tmdb_id'), 'titles', ['tmdb_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('episodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id', 'season', 'number', name='uq_episode_number')
    )
    op.create_index(op.f('ix_episodes_title_id'), 'episodes', ['title_id'], unique=False)
    op.create_table('library_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('WATCHING', 'PLAYING', 'READING', 'PLAN_TO', 'COMPLETED', 'DROPPED', 'ON_HOLD', name='library_status'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('rating IS NULL OR (rating BETWEEN 1 AND 10)', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title_id', name='uq_user_title')
    )
    op.create_index(op.f('ix_library_entries_title_id'), 'library_entries', ['title_id'], unique=False)
    op.create_index(op.f('ix_library_entries_user_id'), 'library_entries', ['user_id'], unique=False)
    op.create_table('watch_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title_id', sa.Uuid(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('offer_type', sa.Enum('STREAM', 'RENT', 'BUY', name='offer_type'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id', 'country', 'provider_name', 'offer_type', name='uq_provider_offer')
    )
    op.create_index(op.f('ix_watch_providers_title_id'), 'watch_providers', ['title_id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('library_entry_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['library_entry_id'], ['library_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_entry_id', 'episode_id', name='uq_entry_episode')
    )
    op.create_index(op.f('ix_progress_episode_id'), 'progress', ['episode_id'], unique=False)
    op.create_index(op.f('ix_progress_library_entry_id'), 'progress', ['library_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_library_entry_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_episode_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_watch_providers_title_id'), table_name='watch_providers')
    op.drop_table('watch_providers')
    op.drop_index(op.f('ix_library_entries_user_id'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_title_id'), table_name='library_entries')
    op.drop_table('library_entries')
    op.drop_index(op.f('ix_episodes_title_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_titles_tmdb_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_rawg_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_media_type'), table_name='titles')
    op.drop_index(op.f('ix_titles_mangadex_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_mal_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_anilist_id'), table_name='titles')
    op.drop_table('titles')
    # Alembic autogenerate does not emit DROP TYPE for native enums — do it here,
    # otherwise the next `upgrade` fails with DuplicateObjectError.
    for enum_name in ("offer_type", "library_status", "media_type"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
